{
 "title": "Aparcament_UdG",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Estat Aparcament", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Estat aparcament",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Data,$__interval),\n  avg(Parking_status) AS \"Parking_status\"\nFROM sensor_cotxe\nWHERE\n  $__timeFilter(Data) AND\n  DevEUI = \"eui-ffffff1000027d34\"\nGROUP BY 1\nORDER BY $__timeGroup(Data,$__interval)"
    }
   ]
  },
  {
   "title": "Panell Horari",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Data,$__interval),\n  avg(Parking_status) AS \"Parking_status\"\nFROM sensor_cotxe\nWHERE\n  $__timeFilter(Data) AND\n  DevEUI = \"eui-ffffff1000027d34\"\nGROUP BY 1\nORDER BY $__timeGroup(Data,$__interval)"
    }
   ]
  },
  {
   "title": "Gràfic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 9, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Data,$__interval),\n  avg(Parking_status) AS \"Parking_status\"\nFROM sensor_cotxe\nWHERE\n  $__timeFilter(Data) AND\n  DevEUI = \"eui-ffffff1000027d34\"\nGROUP BY 1\nORDER BY $__timeGroup(Data,$__interval)"
    }
   ]
  },
  { "title": "Manteniment Sensor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Gràfic de la bateria",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Data,$__interval),\n  avg(Battery_Voltage) AS \"Battery_Voltage\"\nFROM sensor_cotxe\nWHERE\n  $__timeFilter(Data) AND\n  DevEUI = \"eui-ffffff1000027d34\"\nGROUP BY 1\nORDER BY $__timeGroup(Data,$__interval)"
    }
   ]
  },
  {
   "title": "Voltatge de la bateria",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Data,$__interval),\n  avg(Battery_Voltage) AS \"Battery_Voltage\"\nFROM sensor_cotxe\nWHERE\n  $__timeFilter(Data)\nGROUP BY 1\nORDER BY $__timeGroup(Data,$__interval)"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(Data,$__interval),\n  avg(Temp) AS \"Temp\"\nFROM sensor_cotxe\nWHERE\n  $__timeFilter(Data) AND\n  DevEUI = \"eui-ffffff1000027d34\"\nGROUP BY 1\nORDER BY $__timeGroup(Data,$__interval)"
    }
   ]
  }
 ]
}